# values.yaml

persistence:
  enabled: true
  storageClass: "do-block-storage"
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - name: sonarqube.209.38.185.24.nip.io
      path: /
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: []

postgresql:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

sonarqube:
  resources:
    requests:
      cpu: "300m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "750Mi"
